version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: cardapio_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cardapio
      POSTGRES_USER: cardapio_user
      POSTGRES_PASSWORD: cardapio_senha
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: